### ISSUE TITLE
SSL certificate or subdomain not redirect to the right netlify website?

### ISSUE THREAD

**Issue by SamGuay** [BrainhackMTL/school#11]
It seems either the SSL certificate has not been issued yet by Netlify or
That [school.brainhackmtl.org](https://school.brainhackmtl.org) is still pointing to my Netlify account and not @pbellec's account.  

> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for school.brainhackmtl.org. The certificate is only valid for the following names: *.netlify.com, netlify.com
>  
> Error code: SSL_ERROR_BAD_CERT_DOMAIN
>  
> View Certificate
>

**Comment by pbellec** [comment]
I have updated the certificates, and it looks like it's fixed.

But the site does not work anymore, and all the links resolve to the old website.
I think the baseURL config variable needs to be updated.

**Comment by pbellec** [comment]
that was it. Needed a "clear cache and redeploy", but site is now live and looks like everything is working.
