### ISSUE TITLE
preview of the site is broken

### ISSUE THREAD

**Issue by pbellec** [BrainhackMTL/school#22]
can be easily tested on slack, and should be addressable through config.yaml

I thought I had fixed it, but it does not seem to work (or maybe it's a browser caching issue)

**Comment by SamGuay** [comment]
Do you want something different than this?
![image](https://user-images.githubusercontent.com/30598330/77341399-0c7cf000-6d05-11ea-9ec1-252c7ccf7aac.png)

**Comment by pbellec** [comment]
no that's perfect! thanks
