### ISSUE TITLE
Project template + pages

### ISSUE THREAD

**Issue by SamGuay** [BrainhackMTL/school#27]
@pbellec and I think it'd be great to display projects, not only people can follow the progress, but it's a great way to showcase participants' efforts and find out about other projects.

We already need to create a template for their project description, so they will already have the content for their page. This will also be a great way to make a (first) (simple) pull request :bulb:.

**To be done:** 
- [ ] Template for individual project page
  - [ ] Make a _Project archetype_ for adventurous people who wants to try Hugo; or
  - [x] Make a _Project template_ that can be copied and pasted
- [ ] Single layout for individual project page
    - [x] Project Title
    - [x] Project Description
    - [x] Names
    - [x] GitHub repo where the project live (if available)
    - [x] One image
    - [x] 4 keywords
    - [ ] Do we need other infos? 
        - [x] Website hosting the project?

- [x] List layout for individual project pages
  - [x] Find a good-looking card template
  - [x] Include keywords that best describe clusters of project (e.g., EEG, T1w, etc.)

**Comment by pbellec** [comment]
100% agree. I am going to work on it this week end.

**Comment by pbellec** [comment]
Done.

**Comment by complexbrains** [comment]
@all-contributors please add @SamGuay as contributor for bug, content, doc, eventOrganizing, maintenance, review, ideas, code, test, infra, data, design, research, translation.
