### ISSUE TITLE
update the location page

### ISSUE THREAD

**Issue by pbellec** [BrainhackMTL/school#7]
Ideally, there would be a bootstrap layout with 2 columns per row, a picture for each site with a description below, the way we had it before (in `register`)
https://brainhackmtl.github.io/school2019/register.html

Also we need a fifth site, because the new "cog neuro methods bootcamp" should be at pavillon marie victorin, UdeM.

**Comment by SamGuay** [comment]
Since we removed the first week, the layout is wrong. Doesnt really matter since "physical" rooms and not needed anymore.. Do you want me do rearrange this page based on the tools we are going to use as we are going full virtual?

**Comment by pbellec** [comment]
this would be awesome indeed. The different "sites" are still somewhat meaningful, as we will keep our rolling site-based organization. Maybe you could simply add a first site with logos of the remote working tools, and just outline the organization teams for each week.

**Comment by pbellec** [comment]
That would also minimize the work ....
